const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Jogador_Event19_Act1,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.JavaScriptInEvents.Jogador_Event20_Act1,
		C3.JavaScriptInEvents.Jogador_Event21_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Zumbi1_Event6_Act1,
		C3.JavaScriptInEvents.Zumbi1_Event12_Act1
	];
};
self.C3_JsPropNameTable = [
	{direitaMostroZumbi: 0},
	{VidaZumbi: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{zumbi1: 0},
	{Teclado: 0},
	{Mouse: 0},
	{fundo1: 0},
	{muniçao: 0},
	{vidaPlayer: 0},
	{CentrarEm: 0},
	{Cronômetro: 0},
	{jogador: 0},
	{Projétil: 0},
	{tiro: 0},
	{Sprite: 0},
	{carriola: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{chao: 0},
	{caixa: 0},
	{nuvem: 0},
	{nuvem2: 0},
	{fundofase2: 0},
	{nuvem2parte: 0},
	{quadro: 0},
	{Áudio: 0},
	{Sprite2: 0},
	{Âncora: 0},
	{recarga: 0},
	{NumeroDeVida: 0},
	{coraçao: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{barril: 0},
	{carroça2: 0},
	{feno: 0},
	{balde: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{sabrina: 0},
	{Texto: 0},
	{MensagemFInal: 0},
	{fimDoGame: 0},
	{Sprite3: 0},
	{VidaZumbi2: 0},
	{direitaZumbi2: 0},
	{zumbi2: 0},
	{Sprite4: 0},
	{quadro2: 0},
	{Texto2: 0},
	{FonteDeSprites: 0},
	{Texto3: 0},
	{Qntdacertado: 0},
	{vidaplayer: 0}
];

self.InstanceType = {
	zumbi1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	fundo1: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	tiro: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	carriola: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	caixa: class extends self.ISpriteInstance {},
	nuvem: class extends self.ISpriteInstance {},
	nuvem2: class extends self.ISpriteInstance {},
	fundofase2: class extends self.ITiledBackgroundInstance {},
	nuvem2parte: class extends self.ISpriteInstance {},
	quadro: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	recarga: class extends self.ISpriteInstance {},
	NumeroDeVida: class extends self.ISpriteFontInstance {},
	coraçao: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	barril: class extends self.ISpriteInstance {},
	carroça2: class extends self.ISpriteInstance {},
	feno: class extends self.ISpriteInstance {},
	balde: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	sabrina: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	MensagemFInal: class extends self.ISpriteFontInstance {},
	fimDoGame: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	zumbi2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	quadro2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Texto3: class extends self.ITextInstance {}
}